# Generated by Django 2.0.2 on 2018-10-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='punterTipsGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('home_team', models.CharField(max_length=200, null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('away_team', models.CharField(max_length=200, null=True)),
                ('prediction', models.CharField(max_length=100, null=True)),
                ('odds', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Won', 'Won'), ('Lost', 'Lost')], default='running', max_length=10)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='vipTipsGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('home_team', models.CharField(max_length=200, null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('away_team', models.CharField(max_length=200, null=True)),
                ('prediction', models.CharField(max_length=100, null=True)),
                ('odds', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Won', 'Won'), ('Lost', 'Lost')], default='running', max_length=10)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Ticket')),
            ],
        ),
    ]
