# Generated by Django 2.0.3 on 2018-11-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freetipsgame',
            options={'ordering': ['-ticket__date_added']},
        ),
        migrations.AlterModelOptions(
            name='puntertipsgame',
            options={'ordering': ['-ticket__date_added']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='viptipsgame',
            options={'ordering': ['-ticket__date_added']},
        ),
        migrations.RemoveField(
            model_name='freetipsgame',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='puntertipsgame',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='viptipsgame',
            name='date_added',
        ),
    ]
