# Generated by Django 2.0.3 on 2018-12-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_auto_20181118_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, null=True)),
                ('home_team', models.CharField(max_length=200, null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('away_team', models.CharField(max_length=200, null=True)),
                ('prediction', models.CharField(max_length=100, null=True)),
                ('odds', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Won', 'Won'), ('Lost', 'Lost')], default='running', max_length=10)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Ticket')),
            ],
            options={
                'ordering': ['-ticket__date_added'],
            },
        ),
    ]
