# Generated by Django 2.0.3 on 2018-12-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_singlebet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='punterTipsGame',
            new_name='RollTipsGame',
        ),
    ]
